config/routes.rb
module RailsBlog
  # RailsBlog::Routes.mixin(self)
  class Routes
    def self.mixin mapper
      mapper.extend ::RailsBlog::DefaultRoutes
      mapper.send :rails_blog_routes
    end
  end

  module DefaultRoutes
    def rails_blog_routes
      get 'pubs_search' => "pubs_search#pubs_search"

      get "pubs_ordering/:category_type/:category_id",
        action: :ordering,
        controller: :pub_category_rels,
        as: :pubs_ordering

      resources :pub_category_rels do
        collection do
          post :rebuild
        end
      end

      resources :pages do
        collection do
          get :manage
        end
      end

      resources :posts do
        collection do
          get :manage
        end
      end

      resources :hubs do
        collection do
          get :manage
          get :tree
          post :rebuild
        end
      end

      resources :pub_tags do
        collection do
          get :manage
          get :tree
          post :rebuild
          post :create_published
        end
      end

      resources :pubs do
        collection do
          get :manage
        end
      end
    end
  end
end

app/models/concerns/rails_blog/category_model.rb
# include ::RailsBlog::CategoryModel
module RailsBlog
  module CategoryModel
    extend ActiveSupport::Concern

    included do
      include ::RailsBlog::PubStates
      include ::RailsBlog::PubScopes
      include ::RailsBlog::PubContentProcessing

      include ::SimpleSort::Base
      include ::Pagination::Base
      include ::HasMetaData::Holder
      include ::TheStorages::Storage
      include ::FriendlyIdPack::Base
      include ::TheSortableTree::Scopes
      include ::AttachedImages::ItemModel
      include ::Notifications::LocalizedErrors

      acts_as_nested_set scope: :user

      belongs_to :user

      has_many :pub_category_rels,
        as: :category

      has_many :posts,
        through: :pub_category_rels,
        source: :item,
        source_type: :Post

      has_many :pages,
        through: :pub_category_rels,
        source: :item,
        source_type: :Page

      def owner?(check_user = nil)
        return false unless check_user.is_a?(::User)
        user == check_user
      end

    end
  end
end

app/models/concerns/rails_blog/pub_consistency.rb
# include ::RailsBlog::PubConsistency
module RailsBlog
  module PubConsistency
    # extend ActiveSupport::Concern
    # included do; end
    # class_methods do; end

    # Post.all.each{|x| x.keep_consistency! }
    # Page.all.each{|x| x.keep_consistency! }

    def keep_consistency!
      keep_hub_items_consistency!
    end

    def keep_consistency_after_create!
      keep_hub_items_consistency_after_create!
    end

    def keep_consistency_after_update!
      keep_hub_items_consistency_after_update!
    end

    def keep_consistency_after_destroy!
      keep_hub_items_consistency_after_destroy!
    end

    # #############################
    # HubItem consistency
    # #############################

    def keep_hub_items_consistency!
      if pub_category_rels.any?
        keep_consistency_after_update!
      else
        keep_consistency_after_create!
      end
    end

    def keep_hub_items_consistency_after_create!
      pub_category_rels.create(
        item: self,
        item_title: self.title,
        item_state: self.state,
        item_created_at:   self.created_at,
        item_updated_at:   self.updated_at,
        item_published_at: self.published_at
      )
    end

    def keep_hub_items_consistency_after_update!
      pub_category_rels.update_all(
        item_title: self.title,
        item_state: self.state,
        item_created_at:   self.created_at,
        item_updated_at:   self.updated_at,
        item_published_at: self.published_at
      )
    end

    def keep_hub_items_consistency_after_destroy!
      pub_category_rels.delete_all
    end
  end
end

app/models/concerns/rails_blog/pub_content_processing.rb
# include ::RailsBlog::PubContentProcessing
module RailsBlog
  module PubContentProcessing

    extend ActiveSupport::Concern

    included do
      validates :title, :slug, presence: true
    end

    def content_processing_for current_user
      return nil unless current_user

      self.title   = title.squish.strip
      self.intro   = process_content(raw_intro,   current_user)
      self.content = process_content(raw_content, current_user)
    end

    def process_content txt, current_user
      txt = txt.to_s

      # Code Hightlight
      txt = ::ColoredCode.with_pygments(txt)

      ################################
      # Blocks in <noprocessing> tag will be Ignored
      ################################
      al_helper = ::AutoLink.new

      txt = ::ContentForProcessing.process(txt) do |str|
        # MarkDown
        res = ::Markdown2Tags.process(str)
        res = res.empty_p2br

        # AutoLink + Ext Link protection
        res = al_helper.auto_link(res, sanitize: false, html: { target: :_blank, rel: :nofollow })
        res = res.add_nofollow_to_links if !current_user.admin?
        res = res.wrap_nofollow_links_with_noindex

        # Sanitize and Empty lines process
        res = sanitize_for(res, current_user)
      end

      ################################

      txt.strip
    end

    def sanitize_for txt, current_user
      if current_user.admin?
        Sanitize.fragment(txt, Sanitize::Config::ADMIN_RELAXED)
      else
        Sanitize.fragment(txt, Sanitize::Config::BLOGGER_HTML)
      end
    end
  end

end

app/models/concerns/rails_blog/pub_scopes.rb
# include ::RailsBlog::PubScopes
module RailsBlog
  module PubScopes
    extend ActiveSupport::Concern

    included do
      scope :with_users, -> { includes(:user) }
      scope :available_pub_for, ->(user = nil) { user ? for_manage : published }
    end
  end
end

app/controllers/concerns/rails_blog/custom_render_view.rb
# include ::RailsBlog::CustomRenderView

module RailsBlog
  module CustomRenderView
    private

    def render_custom_view opts = {}
      opts = opts.with_indifferent_access

      layout   = opts[:default_layout]
      template = opts[:default_template]
      pub      = opts[:publication]

      if pub
        layout   = pub.view_layout   if pub.view_layout.present?
        template = pub.view_template if pub.view_template.present?
      end

      if layout.present? || template.present?
        render({ layout: layout, template: template }.compact)
      end
    end

  end # CustomRenderView
end # RailsBlog

app/controllers/concerns/rails_blog/pub_category_controller.rb
# include ::RailsBlog::PubCategoryController

module RailsBlog
  module PubCategoryController
    extend ActiveSupport::Concern

    include ::RailsBlog::CustomRenderView
    include ::TheSortableTreeController::Rebuild
    include ::TheSortableTreeController::ExpandNode

    included do
      layout ->{ layout_for_action }

      before_action :set_pub_category, only: %w[ show ]
      before_action :set_editable_pub_category, only: %w[ edit update destroy ]
    end

    # =======================================
    # Public
    # =======================================

    def show
      @pub_categories = @pub_category.children.published.nested_set

      if @pub_category.published? && !@pub_category.owner?(current_user)
        pub_category_klass.increment_counter(:view_counter, @pub_category.id)
      end

      @pub_items = PubCategoryRel
                    .where(category: @pub_category)
                    .includes(:item)
                    .published
                    .reversed_nested_set
                    .simple_sort(params)
                    .pagination(params)
    end

    # =======================================
    # Restricted Area | User
    # =======================================

    def new
      @pub_category = pub_category_klass.new
    end

    def create
      @pub_category = current_user.send(pub_category_name).new(pub_category_params)
      @pub_category.content_processing_for(current_user)

      if @pub_category.save
        @pub_category.try(:keep_consistency_after_create!)
        pub_category_create_success
      else
        pub_category_create_failure
      end
    end

    def edit; end

    def update
      @pub_category.assign_attributes(pub_category_params)
      @pub_category.content_processing_for(current_user)

      if @pub_category.save
        @pub_category.try(:keep_consistency_after_update!)
        pub_category_update_success
      else
        pub_category_reset_changes
        pub_category_update_failure
      end
    end

    def destroy
      @pub_category.destroy
      @pub_category.try(:keep_consistency_after_destroy!)
      redirect_to [:manage, pub_category_name]
    end

    # =======================================
    # Restricted Area | Admin
    # =======================================

    def manage
      @pub_categories = current_user.send(pub_category_name).for_manage.nested_set.simple_sort(params).pagination(params)
    end

    def tree
      @pub_categories = current_user.send(pub_category_name).for_manage.nested_set
    end

    private

    # =======================================
    # Common
    # =======================================

    def pub_category_name
      pub_category_klass.name.tableize
    end

    def set_pub_category
      @pub_category = pub_category_klass.published.friendly_first(params[:id])
      return page_404 unless @pub_category
    end

    def set_editable_pub_category
      @pub_category = pub_category_klass.for_manage.friendly_first(params[:id])
      return page_404 unless @pub_category
    end

    def pub_category_reset_changes
      if @pub_category.changes[:slug]
        @pub_category.slug = @pub_category.changes[:slug].first
      end
    end

    def pub_category_params
      param_name = pub_category_klass.table_name.singularize

      params.require(param_name).permit(
        :title,
        :slug,
        :raw_intro,
        :raw_content,
        :state
      )
    end

    # =======================================
    # RESPONDERS
    # =======================================

    def pub_category_create_success
      respond_to do |format|
        format.html do
          redirect_to url_for([:edit, @pub_category]), notice: "Раздел создан"
        end

        format.js do
          render layout: false,
            template: "#{ pub_category_name }/json/create.success.json.jbuilder"
        end
      end
    end

    def pub_category_create_failure
      respond_to do |format|
        format.html do
          render "#{ pub_category_name }/new"
        end

        format.js do
          render layout: false,
            template: "#{ pub_category_name }/json/create.errors.json.jbuilder", status: 422
        end
      end
    end

    def pub_category_update_success
      respond_to do |format|
        format.html do
          redirect_to url_for([:edit, @pub_category]), notice: "Раздел обновлен"
        end

        format.js do
          render layout: false,
            template: "#{ pub_category_name }/json/update.success.json.jbuilder"
        end
      end
    end

    def pub_category_update_failure
      respond_to do |format|
        format.html do
          render "#{ pub_category_name }/edit"
        end

        format.js do
          render layout: false,
            template: "#{ pub_category_name }/json/update.errors.json.jbuilder", status: 422
        end
      end
    end

  end # PubCategoryController
end # RailsBlog

app/controllers/concerns/rails_blog/pub_controller.rb
module RailsBlog
  module PubController
    extend ActiveSupport::Concern

    included do
      include ::RailsBlog::CustomRenderView
      include ::TheSortableTreeController::ReversedRebuild

      layout ->{ layout_for_action }

      before_action :set_klass
      before_action :set_pub_and_user, only: %w[
        rebuild show print edit slug view_templates update destroy
      ]
      before_action :set_prev_next_pubs, only: %w[ show ]

      # MAIN IMAGE
      before_action :user_require,   except: %w[ index show ]
      before_action :owner_required, except: %w[ index create show my manage new expand_node ]
      before_action :admin_require,  except: %w[ index show ]
    end

    # Public actions

    # def index; end

    def show
      if @pub.published? && !@pub.owner?(current_user)
        @klass.increment_counter(:view_counter, @pub.id)
      end
    end

    def print
      render layout: false, template: 'rails_blog/pubs/print'
    end

    # Restricted actions

    def my
      @pub_items = @user.send(controller_name).max2min(:id).simple_sort(params).pagination(params)
      render 'rails_blog/pubs/manage'
    end

    def new
      @pub = @klass.new
      render 'rails_blog/pubs/new'
    end

    def create
      @pub = current_user.send(controller_name).new(pub_params)
      @pub.content_processing_for(current_user)

      if @pub.save
        @pub.keep_consistency_after_create!
        redirect_to url_for([:edit, @pub]), notice: "Публикация создана"
      else
        render 'rails_blog/pubs/new'
      end
    end

    def edit
      @hubs  = current_user.hubs.nested_set.for_manage
      render 'rails_blog/pubs/edit'
    end

    def update
      @pub.assign_attributes(pub_params)
      @pub.content_processing_for(current_user)

      if @pub.save
        @pub.keep_consistency_after_update!
        redirect_to url_for([:edit, @pub]), notice: "Публикация обновлена"
      else
        @pub.update_attachment_fields(:main_image)
        render 'rails_blog/pubs/edit'
      end
    end

    def destroy
      @pub.destroy
      @pub.keep_consistency_after_destroy!
      redirect_to cabinet_url
    end

    def manage
      @pub_items = if current_user.admin?
        @klass.max2min(:id).simple_sort(params).pagination(params)
      else
        @user.send(controller_name).max2min(:id).simple_sort(params).pagination(params)
      end

      render 'rails_blog/pubs/manage'
    end

    def slug
      render 'rails_blog/pubs/slug'
    end

    def view_templates
      render 'rails_blog/pubs/view_templates'
    end

    private

    def set_klass
      @klass      = controller_name.classify.constantize
      @klass_name = controller_name.singularize.to_sym
    end

    def pub_id
      params[:id]      ||
      params[:post_id] ||
      params[:page_id]
    end

    def set_pub_and_user
      @pub = @klass
              .with_users
              .available_pub_for(current_user)
              .friendly_first(pub_id)

      return page_404 unless @pub

      @user = @pub.user
      @owner_check_object = @pub
    end

    def set_prev_next_pubs
      return unless @pub
      base_rel = @klass.available_pub_for(current_user)
      @next_pub = base_rel.where("#{ @klass.table_name }.created_at < ?", @pub.created_at).last
      @prev_pub = base_rel.where("#{ @klass.table_name }.created_at > ?", @pub.created_at).first
    end

    # MAIN IMAGE
    def user_id
      params[:user] || params[:user_id]
    end

    def pub_params
      # TODO: user_id for create
      # TODO: user_id for update only for moderator|admin

      params.require(@klass_name).permit(
        :slug,

        :hub_id,
        :user_id,

        :main_image,

        :title,
        :raw_intro,
        :raw_content,
        :state,

        :editor_type,

        :view_layout,
        :view_template
      )
    end
  end

end

app/controllers/pubs_controller.rb
class PubsController < RailsBlogController
  def index
    @hub       = Hub.published.friendly_first(:main)
    @root_hubs = Hub.nested_set.roots.published

    sub_sql = PubCategoryRel
                .published
                .where(category: @hub)
                .select(%{ DISTINCT ON ("item_id", "item_type") * })
                .to_sql

    @pub_items = PubCategoryRel
                  .from("(#{ sub_sql }) pub_category_rels")
                  .includes(:item)
                  .max2min([:id])
                  .simple_sort(params)
                  .pagination(params)
  end

  # =======================================
  # Restricted Area | Admin
  # =======================================

  def manage
    sub_sql = PubCategoryRel
                .for_manage
                .select(%{ DISTINCT ON ("item_id", "item_type") * })
                .to_sql

    @pub_items = PubCategoryRel
                  .from("(#{ sub_sql }) pub_category_rels")
                  .includes(:item)
                  .max2min([:id])
                  .simple_sort(params)
                  .pagination(params)
  end
end

app/controllers/rails_blog_controller.rb
class RailsBlogController < ApplicationController
  # USE THIS METHODS WHEN YOU NEED TO SKIP AUTH FILTERS
  #
  # skip_before_filter :authenticate_user!,   only: [:method_name]
  # skip_before_filter :blog_admin_required!, only: [:method_name]

  before_action :authenticate_user!,   except: %w[ index show ]
  before_action :blog_admin_required!, except: %w[ index show ]
  before_action :owner_required,       except: %w[ index show ]

  layout ->{ layout_for_action }

  private

  def blog_admin_required!
    redirect_to root_path unless current_user.try(:admin?)
  end

  def layout_for_action
    return 'rails_blog_frontend' if %w[ index show ].include?(action_name)
    'rails_blog_backend'
  end
end

app/views/rails_blog/pubs/colored_code_css.html.slim
- content_for :css_addons do
  style(type="text/css")
    | .highlight{ background: #272822; color: #fff; padding: 20px; max-width: 598px; overflow: auto; }
    | .highlight pre{ font-family: 'Anonymous Pro', Arial, serif !important; font-weight: 400; }
    | .highlighttable{ width: 100%; max-width: 620px; line-height: 150% !important; font-size: 16px !important; }
    | .highlighttable td { padding: 0 !important }
    | .highlighttable td.linenos{ width: 1%; color: #bbb; padding: 20px 5px !important; background: #033a8d; }
    | .highlight .s{ text-decoration: none !important; }
    = ::ColoredCode.with_pygments_css(:monokai).to_s.noendl

app/views/rails_blog/pubs/edit.html.slim
- content_for :title do
  | Правка: #{ @pub.title }

= render template: 'layouts/items/header_footer'

- if @pub.editor_type == 'ckeditor'
  = render template: 'common/editor/ckeditor'

- if @pub.editor_type == 'ptz_editor'
  = render template: 'common/editor/ptz_editor'

.ptz_theme-0.m20
  span.mr20= link_to 'Кабинет',  cabinet_path, class: 'ptz_btn ptz_size-16'
  span.mr20= link_to 'Просмотр', @pub, class: 'ptz_btn ptz_size-16'
  span.mr20= link_to 'Публикации', manage_pubs_path, class: 'ptz_btn ptz_size-16'

.m20
  .mb30.fs22 Редактировать Публикацию

  = render partial: 'notifications/form', locals: { object: @pub }

  .ptz_tabs(ptz_tabs-scope='pub-edit')
    .ptz_tabs--holder
      .ptz_tabs--item.ptz_tabs--active(ptz_tab-id='form') Основные данные
      .ptz_tabs--item(ptz_tab-id='storage') Файлы
      .ptz_tabs--item(ptz_tab-id='main_image')
        | Картинки
        '
        span.js--attached-images--count
          = !(items_count = @pub.attached_images.count).zero? ? items_count : nil

      .ptz_tabs--item(ptz_tab-id='hubs')
        | Разделы
        '
        span.js--hubs--count
          = !(items_count = @pub.hubs.count).zero? ? items_count : nil

      .ptz_tabs--item(ptz_tab-id='pub_tags')
        | Теги
        '
        span.js--pub-tags--count
          = !(items_count = @pub.pub_tags.count).zero? ? items_count : nil

      .ptz_tabs--item(ptz_tab-id='seo') SEO
      .ptz_tabs--item(ptz_tab-id='rel-pubs') Публикации +

    .mt20.mb20

      .ptz_tabs--content-item.ptz_tabs--active(ptz_tab-content='form')
        .ptz_theme-0= render template: 'pubs/edit/form'

      .ptz_tabs--content-item(ptz_tab-content='main_image')
        .ptz_theme-0= render template: 'attached_images/edit/attached_images', locals: { item: @pub }

      .ptz_tabs--content-item(ptz_tab-content='storage')
        .ptz_theme-0= render template: 'pubs/edit/storage', locals: { item: @pub }

      .ptz_tabs--content-item(ptz_tab-content='seo')
        .ptz_theme-0
          .mb30= render template: 'pubs/edit/slug'
          .mb30= render template: 'meta_data/edit/meta_data', locals: { item: @pub }

      .ptz_tabs--content-item(ptz_tab-content='hubs')
        .ptz_theme-0= render template: 'pubs/edit/hubs'

      .ptz_tabs--content-item(ptz_tab-content='pub_tags')
        .ptz_theme-0= render template: 'pubs/edit/pub_tags', locals: { pub: @pub }

      .ptz_tabs--content-item(ptz_tab-content='rel-pubs')
        .fs15 Здесь будет можно указать связанные посты

app/views/rails_blog/pubs/index.html.slim
- content_for :title do
  | Rails Blog

= render template: 'app_view/layouts/items/header_footer'

.m20
  .tar.fs15.mb20
    = render template: 'common/pages_and_reset'

  = render template: 'pubs/list', locals: { pubs: @pub_items }
  = render template: 'common/paginator', locals: { items: @pub_items }

app/views/rails_blog/pubs/list.html.slim
.ptz_theme-0
  - if pubs.blank?
    .ptz_div-0.fs18.p20 Здесь ничего нет
  - else
    table.ptz_table-0.w100p.fs16
      thead.tal
        tr
          th.p20.w50
          th.p20.w100p.br-off = link_to 'Название ↕',        simple_sort_url(:item_title)
          th.p20.w100p.br-off = link_to 'Типу ↕',            simple_sort_url(:item_type)
          th.p20.w150.br-off  = link_to 'Дата создания ↕',   simple_sort_url(:item_created_at)
          th.p20.w150.br-off  = link_to 'Дата публикации ↕', simple_sort_url(:item_published_at)

      tbody
        - pubs.each do |pub_item|
          - pub = pub_item.try(:item) || pub_item

          tr
            td.p20
              = link_to pub do
                = image_tag pub.main_image_url(:v640x480), style: 'width:120px'
            td.p20.lh120
              = link_to pub.title, pub
            td.p20
              = t pub_item.item_type, scope: :pubs
            td.p20.lh120
              = raw I18n.l(pub.created_at, format: raw("%-d %B %Y %H:%M"))
            td.p20.lh120
              - if pub.published_at.present?
                - date = pub.published_at
                = raw I18n.l(date, format: raw("%-d %B %Y %H:%M"))
              - else
                | &mdash;

app/views/rails_blog/pubs/manage.html.slim
- content_for :title do
  | Publications#index

= render template: 'app_view/layouts/items/header_footer'

- content_for :left_sidebar do

  .ptz_theme-0.m20
    div= link_to 'Кабинет',  cabinet_path, class: 'ptz_btn ptz_size-16 w100p'
    hr.ptz_hr-0
    .mb20= link_to 'Создать страницу', new_page_path, class: 'ptz_btn ptz_size-16 w100p'
    .mb20= link_to 'Создать статью',   new_post_path, class: 'ptz_btn ptz_size-16 w100p'

.m20
  .fs22.mb15 Все публикации
  = render template: 'rails_blog/pubs/manager_table', locals: { pubs:  @pub_items }
  .ptz_theme-0
    = render template: 'common/paginator',   locals: { items: @pub_items }

app/views/rails_blog/pubs/manager_table.html.slim
.tar.fs15.mb25
  = render template: 'common/pages_and_reset'

.ptz_theme-0
  table.ptz_table-0.w100p.fs16
    thead.tal
      th.p20.br-off.w50   = link_to 'ID ↕', simple_sort_url(:id)
      th.p20.br-off.w100p = link_to 'Название ↕', simple_sort_url(:item_title)
      th.p20.br-off.w150  = link_to 'Статус ↕', simple_sort_url(:item_state)
      th.p20.br-off.w50   Правка

    tbody
      - pubs.each do |pub_item|
        - pub = pub_item.try(:item) || pub_item

        tr
          td.p20.w50
            = pub_item.id
          td.p20.w100p
            = link_to pub.title, pub
          td.p20.w150
            = t pub.state, scope: :state
          td.p20.w150.tac
            = link_to [:edit, pub] do
              i.fa.fa-edit

app/views/rails_blog/pubs/new.html.slim
- content_for :title do
  | Новая публикация

= render template: 'layouts/items/header_footer'

- content_for :left_sidebar do
  .m20
    .mb20= link_to 'Кабинет',  cabinet_path, class: 'ptz_btn ptz_size-16 w100p'
    .mb20= link_to 'Публикации', manage_pubs_path, class: 'ptz_btn ptz_size-16 w100p'

.m20
  .mb30.fs22 Создать Публикацию

  = render partial: 'notifications/form', locals: { object: @pub, format: :json }

  .ptz_theme-0
    .ptz_div-0.w800
      = form_for @pub do |f|
        .m20
          .mb15
            = f.label :title, 'Заголовок', class: 'block fs13 mb5'
            = f.text_field :title, class: 'ptz_input ptz_size-15 w500', data: { role: :pub_title }

          - if current_user.admin?
            .mb15
              = f.label :editor_type, 'Тип редактора', class: 'block fs13 mb5'

              - options = options_for_select({ 'Пользовательский' => 'ckeditor', 'Профессиональный' => 'ptz_editor' }, @pub.state)
              = f.select :editor_type, options, {}, autocomplete: :off, class: 'ptz_input ptz_select ptz_size-15 w200'

          .tal
            = f.submit 'Создать', class: 'ptz_btn ptz_size-20'

app/views/rails_blog/pubs/show.html.slim
- content_for :title do
  = @pub.title

= render template: 'app_view/layouts/items/header_footer'

= render template: 'common/admin/controls/pub'

- if @pub.editor_type == 'ptz_editor'
  = render template: 'rails_blog/pubs/colored_code_css'

.ptz_theme-0
  .ptz_typo-0
    h1= @pub.title
    .mb10= raw @pub.intro
    .mb10= raw @pub.content