config/routes.rb
module RailsBlog
  # RailsBlog::Routes.mixin(self)
  class Routes
    def self.mixin mapper
      mapper.extend ::RailsBlog::DefaultRoutes
      mapper.send :rails_blog_routes
    end
  end

  module DefaultRoutes
    def rails_blog_routes
      get 'pubs_search' => "pubs_search#pubs_search"

      get "pubs_ordering/:category_type/:category_id",
        action: :ordering,
        controller: :pub_category_rels,
        as: :pubs_ordering

      resources :pub_category_rels do
        collection do
          post :rebuild
        end
      end

      resources :pages do
        collection do
          get :manage
        end
      end

      resources :posts do
        collection do
          get :manage
        end
      end

      resources :hubs do
        collection do
          get :manage
          get :tree
          post :rebuild
        end
      end

      resources :pub_tags do
        collection do
          get :manage
          get :tree
          post :rebuild
          post :create_published
        end
      end

      resources :pubs do
        collection do
          get :manage
        end
      end
    end
  end
end

app/models/concerns/rails_blog/category_model.rb
# include ::RailsBlog::CategoryModel
module RailsBlog
  module CategoryModel
    extend ActiveSupport::Concern

    included do
      include ::RailsBlog::PubStates
      include ::RailsBlog::PubScopes
      include ::RailsBlog::PubContentProcessing

      include ::SimpleSort::Base
      include ::Pagination::Base
      include ::HasMetaData::Holder
      include ::TheStorages::Storage
      include ::FriendlyIdPack::Base
      include ::TheSortableTree::Scopes
      include ::AttachedImages::ItemModel
      include ::Notifications::LocalizedErrors

      acts_as_nested_set scope: :user

      belongs_to :user

      has_many :pub_category_rels,
        as: :category

      has_many :posts,
        through: :pub_category_rels,
        source: :item,
        source_type: :Post

      has_many :pages,
        through: :pub_category_rels,
        source: :item,
        source_type: :Page

      def owner?(check_user = nil)
        return false unless check_user.is_a?(::User)
        user == check_user
      end

    end
  end
end

app/models/concerns/rails_blog/pub_consistency.rb
# include ::RailsBlog::PubConsistency
module RailsBlog
  module PubConsistency
    # extend ActiveSupport::Concern
    # included do; end
    # class_methods do; end

    # Post.all.each{|x| x.keep_consistency! }
    # Page.all.each{|x| x.keep_consistency! }

    def keep_consistency!
      keep_hub_items_consistency!
    end

    def keep_consistency_after_create!
      keep_hub_items_consistency_after_create!
    end

    def keep_consistency_after_update!
      keep_hub_items_consistency_after_update!
    end

    def keep_consistency_after_destroy!
      keep_hub_items_consistency_after_destroy!
    end

    # #############################
    # HubItem consistency
    # #############################

    def keep_hub_items_consistency!
      if pub_category_rels.any?
        keep_consistency_after_update!
      else
        keep_consistency_after_create!
      end
    end

    def keep_hub_items_consistency_after_create!
      pub_category_rels.create(
        item: self,
        item_title: self.title,
        item_state: self.state,
        item_created_at:   self.created_at,
        item_updated_at:   self.updated_at,
        item_published_at: self.published_at
      )
    end

    def keep_hub_items_consistency_after_update!
      pub_category_rels.update_all(
        item_title: self.title,
        item_state: self.state,
        item_created_at:   self.created_at,
        item_updated_at:   self.updated_at,
        item_published_at: self.published_at
      )
    end

    def keep_hub_items_consistency_after_destroy!
      pub_category_rels.delete_all
    end
  end
end

app/models/concerns/rails_blog/pub_content_processing.rb
# include ::RailsBlog::PubContentProcessing
module RailsBlog
  module PubContentProcessing

    extend ActiveSupport::Concern

    included do
      validates :title, :slug, presence: true
    end

    def content_processing_for current_user
      return nil unless current_user

      self.title   = title.squish.strip
      self.intro   = process_content(raw_intro,   current_user)
      self.content = process_content(raw_content, current_user)
    end

    def process_content txt, current_user
      txt = txt.to_s

      # Code Hightlight
      txt = ::ColoredCode.with_pygments(txt)

      ################################
      # Blocks in <noprocessing> tag will be Ignored
      ################################
      al_helper = ::AutoLink.new

      txt = ::ContentForProcessing.process(txt) do |str|
        # MarkDown
        res = ::Markdown2Tags.process(str)
        res = res.empty_p2br

        # AutoLink + Ext Link protection
        res = al_helper.auto_link(res, sanitize: false, html: { target: :_blank, rel: :nofollow })
        res = res.add_nofollow_to_links if !current_user.admin?
        res = res.wrap_nofollow_links_with_noindex

        # Sanitize and Empty lines process
        res = sanitize_for(res, current_user)
      end

      ################################

      txt.strip
    end

    def sanitize_for txt, current_user
      if current_user.admin?
        Sanitize.fragment(txt, Sanitize::Config::ADMIN_RELAXED)
      else
        Sanitize.fragment(txt, Sanitize::Config::BLOGGER_HTML)
      end
    end
  end

end

app/models/concerns/rails_blog/pub_scopes.rb
# include ::RailsBlog::PubScopes
module RailsBlog
  module PubScopes
    extend ActiveSupport::Concern

    included do
      scope :with_users, -> { includes(:user) }
      scope :available_pub_for, ->(user = nil) { user ? for_manage : published }
    end
  end
end

app/controllers/concerns/rails_blog/custom_render_view.rb
# include ::RailsBlog::CustomRenderView

module RailsBlog
  module CustomRenderView
    private

    def render_custom_view opts = {}
      opts = opts.with_indifferent_access

      layout   = opts[:default_layout]
      template = opts[:default_template]
      pub      = opts[:publication]

      if pub
        layout   = pub.view_layout   if pub.view_layout.present?
        template = pub.view_template if pub.view_template.present?
      end

      if layout.present? || template.present?
        render({ layout: layout, template: template }.compact)
      end
    end

  end # CustomRenderView
end # RailsBlog

app/controllers/concerns/rails_blog/pub_category_controller.rb
# include ::RailsBlog::PubCategoryController

module RailsBlog
  module PubCategoryController
    extend ActiveSupport::Concern

    include ::RailsBlog::CustomRenderView
    include ::TheSortableTreeController::Rebuild
    include ::TheSortableTreeController::ExpandNode

    included do
      layout ->{ layout_for_action }

      before_action :set_pub_category, only: %w[ show ]
      before_action :set_editable_pub_category, only: %w[ edit update destroy ]
    end

    # =======================================
    # Public
    # =======================================

    def show
      @pub_categories = @pub_category.children.published.nested_set

      if @pub_category.published? && !@pub_category.owner?(current_user)
        pub_category_klass.increment_counter(:view_counter, @pub_category.id)
      end

      @pub_items = PubCategoryRel
                    .where(category: @pub_category)
                    .includes(:item)
                    .published
                    .reversed_nested_set
                    .simple_sort(params)
                    .pagination(params)
    end

    # =======================================
    # Restricted Area | User
    # =======================================

    def new
      @pub_category = pub_category_klass.new
    end

    def create
      @pub_category = current_user.send(pub_category_name).new(pub_category_params)
      @pub_category.content_processing_for(current_user)

      if @pub_category.save
        @pub_category.try(:keep_consistency_after_create!)
        pub_category_create_success
      else
        pub_category_create_failure
      end
    end

    def edit; end

    def update
      @pub_category.assign_attributes(pub_category_params)
      @pub_category.content_processing_for(current_user)

      if @pub_category.save
        @pub_category.try(:keep_consistency_after_update!)
        pub_category_update_success
      else
        pub_category_reset_changes
        pub_category_update_failure
      end
    end

    def destroy
      @pub_category.destroy
      @pub_category.try(:keep_consistency_after_destroy!)
      redirect_to [:manage, pub_category_name]
    end

    # =======================================
    # Restricted Area | Admin
    # =======================================

    def manage
      @pub_categories = current_user.send(pub_category_name).for_manage.nested_set.simple_sort(params).pagination(params)
    end

    def tree
      @pub_categories = current_user.send(pub_category_name).for_manage.nested_set
    end

    private

    # =======================================
    # Common
    # =======================================

    def pub_category_name
      pub_category_klass.name.tableize
    end

    def set_pub_category
      @pub_category = pub_category_klass.published.friendly_first(params[:id])
      return page_404 unless @pub_category
    end

    def set_editable_pub_category
      @pub_category = pub_category_klass.for_manage.friendly_first(params[:id])
      return page_404 unless @pub_category
    end

    def pub_category_reset_changes
      if @pub_category.changes[:slug]
        @pub_category.slug = @pub_category.changes[:slug].first
      end
    end

    def pub_category_params
      param_name = pub_category_klass.table_name.singularize

      params.require(param_name).permit(
        :title,
        :slug,
        :raw_intro,
        :raw_content,
        :state
      )
    end

    # =======================================
    # RESPONDERS
    # =======================================

    def pub_category_create_success
      respond_to do |format|
        format.html do
          redirect_to url_for([:edit, @pub_category]), notice: "Раздел создан"
        end

        format.js do
          render layout: false,
            template: "#{ pub_category_name }/json/create.success.json.jbuilder"
        end
      end
    end

    def pub_category_create_failure
      respond_to do |format|
        format.html do
          render "#{ pub_category_name }/new"
        end

        format.js do
          render layout: false,
            template: "#{ pub_category_name }/json/create.errors.json.jbuilder", status: 422
        end
      end
    end

    def pub_category_update_success
      respond_to do |format|
        format.html do
          redirect_to url_for([:edit, @pub_category]), notice: "Раздел обновлен"
        end

        format.js do
          render layout: false,
            template: "#{ pub_category_name }/json/update.success.json.jbuilder"
        end
      end
    end

    def pub_category_update_failure
      respond_to do |format|
        format.html do
          render "#{ pub_category_name }/edit"
        end

        format.js do
          render layout: false,
            template: "#{ pub_category_name }/json/update.errors.json.jbuilder", status: 422
        end
      end
    end

  end # PubCategoryController
end # RailsBlog

app/controllers/concerns/rails_blog/pub_controller.rb
module RailsBlog
  module PubController
    extend ActiveSupport::Concern

    included do
      include ::RailsBlog::CustomRenderView
      include ::TheSortableTreeController::ReversedRebuild

      layout ->{ layout_for_action }

      before_action :set_klass
      before_action :set_pub_and_user, only: %w[
        rebuild show print edit slug view_templates update destroy
      ]
      before_action :set_prev_next_pubs, only: %w[ show ]

      # MAIN IMAGE
      before_action :user_require,   except: %w[ index show ]
      before_action :owner_required, except: %w[ index create show my manage new expand_node ]
      before_action :admin_require,  except: %w[ index show ]
    end

    # Public actions

    # def index; end

    def show
      if @pub.published? && !@pub.owner?(current_user)
        @klass.increment_counter(:view_counter, @pub.id)
      end
    end

    def print
      render layout: false, template: 'rails_blog/pubs/print'
    end

    # Restricted actions

    def my
      @pub_items = @user.send(controller_name).max2min(:id).simple_sort(params).pagination(params)
      render 'rails_blog/pubs/manage'
    end

    def new
      @pub = @klass.new
      render 'rails_blog/pubs/new'
    end

    def create
      @pub = current_user.send(controller_name).new(pub_params)
      @pub.content_processing_for(current_user)

      if @pub.save
        @pub.keep_consistency_after_create!
        redirect_to url_for([:edit, @pub]), notice: "Публикация создана"
      else
        render 'rails_blog/pubs/new'
      end
    end

    def edit
      @hubs  = current_user.hubs.nested_set.for_manage
      render 'rails_blog/pubs/edit'
    end

    def update
      @pub.assign_attributes(pub_params)
      @pub.content_processing_for(current_user)

      if @pub.save
        @pub.keep_consistency_after_update!
        redirect_to url_for([:edit, @pub]), notice: "Публикация обновлена"
      else
        @pub.update_attachment_fields(:main_image)
        render 'rails_blog/pubs/edit'
      end
    end

    def destroy
      @pub.destroy
      @pub.keep_consistency_after_destroy!
      redirect_to cabinet_url
    end

    def manage
      @pub_items = if current_user.admin?
        @klass.max2min(:id).simple_sort(params).pagination(params)
      else
        @user.send(controller_name).max2min(:id).simple_sort(params).pagination(params)
      end

      render 'rails_blog/pubs/manage'
    end

    def slug
      render 'rails_blog/pubs/slug'
    end

    def view_templates
      render 'rails_blog/pubs/view_templates'
    end

    private

    def set_klass
      @klass      = controller_name.classify.constantize
      @klass_name = controller_name.singularize.to_sym
    end

    def pub_id
      params[:id]      ||
      params[:post_id] ||
      params[:page_id]
    end

    def set_pub_and_user
      @pub = @klass
              .with_users
              .available_pub_for(current_user)
              .friendly_first(pub_id)

      return page_404 unless @pub

      @user = @pub.user
      @owner_check_object = @pub
    end

    def set_prev_next_pubs
      return unless @pub
      base_rel = @klass.available_pub_for(current_user)
      @next_pub = base_rel.where("#{ @klass.table_name }.created_at < ?", @pub.created_at).last
      @prev_pub = base_rel.where("#{ @klass.table_name }.created_at > ?", @pub.created_at).first
    end

    # MAIN IMAGE
    def user_id
      params[:user] || params[:user_id]
    end

    def pub_params
      # TODO: user_id for create
      # TODO: user_id for update only for moderator|admin

      params.require(@klass_name).permit(
        :slug,

        :hub_id,
        :user_id,

        :main_image,

        :title,
        :raw_intro,
        :raw_content,
        :state,

        :editor_type,

        :view_layout,
        :view_template
      )
    end
  end

end

app/controllers/pub_tags_controller.rb
class PubTagsController < RailsBlogController
  def pub_category_klass
    ::PubTag
  end

  include ::RailsBlog::PubCategoryController

  def create_published
    set_category
    set_publication
    set_category_publication_relation

    if @pub_category.save
      @pub_category.published!
      @pub_category.try(:keep_consistency_after_create!)

      render layout: false, template: 'pub_tags/json/create_published.success.json.jbuilder'
    else
      render layout: false, template: 'pub_tags/json/create_published.errors.json.jbuilder'
    end
  end

  def index
    @pub_tags = PubTag.published.min2max(:title)
  end

  def show
    super

    render_custom_view(
      default_layout:   'rails_blog_frontend',
      default_template: 'pub_tags/show',
      publication: @pub_category
    )
  end

  # =======================================
  # Restricted Area | Admin
  # =======================================

  def manage
    @pub_tags = PubTag.for_manage.min2max(:title)
  end

  private

  def set_category
    @pub_category = current_user.send(pub_category_name).new(title: params[:title])
    @pub_category.content_processing_for(current_user)
  end

  def set_publication
    klass = params[:pub_type].classify.constantize
    id    = params[:pub_id]

    @pub = current_user.admin? ? \
      klass.find(id) : \
      current_user.send(klass.to_s.tableize).find(id)
  end

  def set_category_publication_relation
    PubCategoryRel.create(category: @pub_category, item: @pub)
  end
end

app/controllers/rails_blog_controller.rb
class RailsBlogController < ApplicationController
  # USE THIS METHODS WHEN YOU NEED TO SKIP AUTH FILTERS
  #
  # skip_before_filter :authenticate_user!,   only: [:method_name]
  # skip_before_filter :blog_admin_required!, only: [:method_name]

  before_action :authenticate_user!,   except: %w[ index show ]
  before_action :blog_admin_required!, except: %w[ index show ]
  before_action :owner_required,       except: %w[ index show ]

  layout ->{ layout_for_action }

  private

  def blog_admin_required!
    redirect_to root_path unless current_user.try(:admin?)
  end

  def layout_for_action
    return 'rails_blog_frontend' if %w[ index show ].include?(action_name)
    'rails_blog_backend'
  end
end

app/helpers/pub_tags_helper.rb
module PubTagsHelper
  def pub_tags_sorted_list
    @pub_tags_list ||= PubTagViewModel.get
  end
end

app/views/rails_blog/pub_tags/edit.html.slim
- @pub_tag = @pub_category

= render template: 'app_view/layouts/items/header_footer'

- content_for :title do
  | Редактировать тег: #{ @pub_tag.title }

.w800.ma.mb20

  .mt20.mb20
    span.mr20= link_to 'Просмотр по тегу', @pub_tag, class: 'ptz_btn ptz_size-14'
    span.mr20= link_to 'Управлять тегами', [:manage, :pub_tags], class: 'ptz_btn ptz_size-14'

  .mb30.fs22 Редактировать тег

  = render partial: 'notifications/form', locals: { object: @pub_tag }

  .ptz_tabs(ptz_tabs-scope='pub-tag-edit')
    .ptz_tabs--holder
      .ptz_tabs--item.ptz_tabs--active(ptz_tab-id='form') Основные данные
      .ptz_tabs--item(ptz_tab-id='slug') URL Адрес
      .ptz_tabs--item(ptz_tab-id='destroy') Удалить

    .mt20.mb20

      .ptz_tabs--content-item.ptz_tabs--active(ptz_tab-content='form')
        .ptz_theme-0= render template: 'pub_tags/edit/form'

      .ptz_tabs--content-item(ptz_tab-content='slug')
        .ptz_theme-0= render template: 'pub_tags/edit/slug'

      .ptz_tabs--content-item(ptz_tab-content='destroy')
        .ptz_theme-0= render template: 'pub_tags/edit/destroy'

app/views/rails_blog/pub_tags/index.html.slim
- content_for :title do
  Теги

= render template: 'app_view/layouts/items/header_footer'

.m20
  .tac.fs20.fw300 Теги

  .ma.w1000
    - @pub_tags = @pub_tags.group_by{|u| u.title.first.mb_chars.upcase.ord }
    - @pub_tags = @pub_tags.to_a.sort
    - rus, eng  = @pub_tags .partition{|item| item.first > 1000 }

    .mt40.mb40.fs26 Русский алфавит

    - rus.each do |alpha, glossary_array|
      .fs18.mb15= alpha.chr
      .mb20
        - glossary_array.sort{|a,b| a.title.mb_chars.downcase <=> b.title.mb_chars.downcase}.each do |tag|
          = link_to tag.title, tag, class: "ptz_btn ptz_size-13 mr5 mb5"

    .mt40.mb40.fs26 Английский алфавит

    - eng.each do |alpha, glossary_array|
      .fs18.mb15= alpha.chr
      .mb20
        - glossary_array.sort{|a,b| a.title.mb_chars.downcase <=> b.title.mb_chars.downcase}.each do |tag|
          = link_to tag.title, tag, class: "ptz_btn ptz_size-13 mr5 mb5"

app/views/rails_blog/pub_tags/manage.html.slim
= render template: 'app_view/layouts/items/header_footer'

- content_for :title do
  | Теги публикаций | Управление

.m20
  .fw300.fs24.mb25 Редактировать теги

  .mb60
    .app--div-1.p20
      = render template: 'new_form'

    .js--pub-tag-new.mt20

  ruby:
    pub_tags = @pub_tags.group_by{|u| u.title.first.mb_chars.upcase.ord }
    rus, eng = pub_tags.partition{|item| item.first > 1000 }

  - if rus.size > 0
    .mt40.mb40.fs26 Русский алфавит

    - rus.sort.each do |alpha, glossary_array|
      .fs18.mb15= alpha.chr
      .mb20
        - glossary_array.sort{|a,b| a.title.mb_chars.downcase <=> b.title.mb_chars.downcase}.each do |tag|
          = link_to tag.title, [:edit, tag], class: "pub-tag--state-#{tag.state} ptz_btn ptz_size-13 mr5 mb5"

  - if eng.size > 0
    .mt40.mb40.fs26 Английский алфавит

    - eng.sort.each do |alpha, glossary_array|
      .fs18.mb15= alpha.chr
      .mb20
        - glossary_array.sort{|a,b| a.title.mb_chars.downcase <=> b.title.mb_chars.downcase}.each do |tag|
          = link_to tag.title, [:edit, tag], class: "pub-tag--state-#{tag.state} ptz_btn ptz_size-13 mr5 mb5"

app/views/rails_blog/pub_tags/new_form.html.slim
= form_for PubTag.new, remote: true, html: { class: 'js--pub-tag-new--form' } do |f|
  .mb25= f.text_field :title, class: 'ptz_input ptz_size-15 w500 js--new-pub-tag-form', placeholder: 'Имя нового тега', autocomplete: :off
  = f.submit 'Создать новый тег', class: 'ptz_btn ptz_size-15'

app/views/rails_blog/pub_tags/pub_list.html.slim
.hidden style='display:none'
  = form_for PubTag.new, remote: true, html: { class: 'js--pub-tags-new--select-2-form' } do |f|
    = f.hidden_field :title, autocomplete: :off

  = form_tag '#', remote: true, class: 'js--shop-category-rels--form', data: { type: :json } do
    = hidden_field_tag :category_type, :PubTag
    = hidden_field_tag :category_id, '?'

    = hidden_field_tag :pub_type, @pub.class
    = hidden_field_tag :pub_id,   @pub.id

    = hidden_field_tag :checked

ruby:
  tags = pub.pub_tags

  pub_tags = PubTag.published.min2max(:title)
  pub_tags = pub_tags.group_by{|u| u.title.first.mb_chars.upcase.ord }

  rus, eng = pub_tags.partition{|item| item.first > 1000 }
  rus_tags = rus.sort
  eng_tags = eng.sort

  sorted_tags = rus_tags + eng_tags
  sorted_tags = sorted_tags.map(&:last).flatten

  selected_tags = tags.map{|pub_tag| pub_tag.slug }
  tag_options = options_for_select(sorted_tags.map{|pub_tag| [pub_tag.title, pub_tag.slug] }, selected_tags)

.ma.w1000.mb40
  = select_tag :pub_tags_selector, tag_options, multiple: :multiple, autocomplete: :off, class: 'js--pub-tags-select2 pub-tags-select2 w80p', placeholder: 'Выбор тегов'

.ma.w1000
  - if rus_tags.size > 0
    .mt40.mb40.fs26 Русский алфавит

    - rus_tags.each do |alpha, glossary_array|
      .fs18.mb15= alpha.chr
      .mb20
        - glossary_array.sort{|a,b| a.title.mb_chars.downcase <=> b.title.mb_chars.downcase}.each do |tag|
          - if tags.include?(tag)
            = link_to tag.title, jsvoid, class: "js--pub-tags--current--#{ tag.slug } js--pub-tags-rels--delete ptz--btn ptz--size-13 mr5 mb5 b", data: { 'category-type' => tag.class.to_s, 'category-id' => tag.id }
          - else
            = link_to tag.title, jsvoid, class: "js--pub-tags--regular--#{ tag.slug } js--pub-tags-rels--create ptz--btn ptz--size-13 mr5 mb5", remote: true, data: { 'category-type' => tag.class.to_s, 'category-id' => tag.id }

  - if eng_tags.size > 0
    .mt40.mb40.fs26 Английский алфавит

    - eng_tags.each do |alpha, glossary_array|
      .fs18.mb15= alpha.chr
      .mb20
        - glossary_array.sort{|a,b| a.title.mb_chars.downcase <=> b.title.mb_chars.downcase}.each do |tag|
          - if tags.include?(tag)
            = link_to tag.title, jsvoid, class: "js--pub-tags--current--#{ tag.slug } js--pub-tags-rels--delete ptz--btn ptz--size-13 mr5 mb5 b", data: { 'category-type' => tag.class.to_s, 'category-id' => tag.id }
          - else
            = link_to tag.title, jsvoid, class: "js--pub-tags--regular--#{ tag.slug } js--pub-tags-rels--create ptz--btn ptz--size-13 mr5 mb5", remote: true, data: { 'category-type' => tag.class.to_s, 'category-id' => tag.id }

app/views/rails_blog/pub_tags/show.html.slim
- content_for :title do
  = @pub_category.title

= render template: 'app_view/layouts/items/header_footer'

- if current_user.try(:admin?)
  .mt20.mb20
    = link_to 'Редактировать', [:edit, @pub_category], class: 'ptz_btn mr20'
    = link_to 'Порядок публикаций', pubs_ordering_path(@pub_category.class, @pub_category.to_param), class: 'ptz_btn'

= render template: 'pubs/list', locals: { pubs: @pub_items }
= render template: 'common/paginator', locals: { items: @pub_items }

app/views/rails_blog/pub_tags/tags_list.html.slim
ruby:
  tags = pub.pub_tags
  rus_tags, eng_tags, sorted_tags = pub_tags_sorted_list

- if rus_tags.size > 0
  .mt40.mb40.fs26 Русский алфавит

  - rus_tags.each do |alpha, glossary_array|
    .fs18.mb15= alpha.chr
    .mb20
      - glossary_array.sort{|a,b| a.title.mb_chars.downcase <=> b.title.mb_chars.downcase}.each do |tag|
        ruby:
          basic_css  = "js--pub-tag--#{ tag.slug } js--pub-tag--btn pub-tag--btn ptz_btn ptz_size-13 mr5 mb5"
          basic_data = { class: tag.class.to_s, id: tag.id }

        - if tags.include?(tag)
          = link_to tag.title, jsvoid, class: "#{ basic_css } selected", data: basic_data
        - else
          = link_to tag.title, jsvoid, class: "#{ basic_css } regular", data: basic_data

- if eng_tags.size > 0
  .mt40.mb40.fs26 Английский алфавит

  - eng_tags.each do |alpha, glossary_array|
    .fs18.mb15= alpha.chr
    .mb20
      - glossary_array.sort{|a,b| a.title.mb_chars.downcase <=> b.title.mb_chars.downcase}.each do |tag|
        ruby:
          basic_css  = "js--pub-tag--#{ tag.slug } js--pub-tag--btn pub-tag--btn ptz_btn ptz_size-13 mr5 mb5"
          basic_data = { class: tag.class.to_s, id: tag.id }

        - if tags.include?(tag)
          = link_to tag.title, jsvoid, class: "#{ basic_css } selected", data: basic_data
        - else
          = link_to tag.title, jsvoid, class: "#{ basic_css } regular", data: basic_data

app/views/rails_blog/pub_tags/tags_list_forms.html.slim
.hidden style='display:none'
  = form_for PubTag.new, url: create_published_pub_tags_url, remote: true, data: { type: :json }, html: { class: 'js--pub-tag-create-and-pub--form' } do |f|
    = hidden_field_tag :title, autocomplete: :off

    = hidden_field_tag :pub_type, pub.class
    = hidden_field_tag :pub_id,   pub.id

.hidden style='display:none'
  = form_tag pub_category_rels_url, remote: true, class: 'js--pub-tag-rels--form', data: { type: :json } do
    = hidden_field_tag :category_type, :PubTag
    = hidden_field_tag :category_id, '?'

    = hidden_field_tag :pub_type, pub.class
    = hidden_field_tag :pub_id,   pub.id

    = hidden_field_tag :checked

app/views/rails_blog/pub_tags/tags_list_select2.html.slim
ruby:
  tags = pub.pub_tags
  rus_tags, eng_tags, sorted_tags = pub_tags_sorted_list
  selected_tags = tags.map{|pub_tag| pub_tag.slug }

  tag_options = options_for_select(sorted_tags.map do |pub_tag|
    html_params = {
      class: "js--pub-tag-select2-option--#{ pub_tag.id }",
      data: { id: pub_tag.id }
    }

    [pub_tag.title, pub_tag.slug, html_params]
  end, selected_tags)

= select_tag :pub_tags_selector, tag_options, multiple: :multiple, autocomplete: :off, class: 'js--pub-tag-select2 pub-tag-select2 w80p', placeholder: 'Выбор тегов'